name: ocp-tool2
channels:
  - conda-forge
  - eumetsat
dependencies:
  - netcdf4
  - matplotlib
  - basemap
  - pandas
  - pyyaml
  - python-eccodes
  - git
  - pip
  - jupyterlab
  - notebook
  - tqdm
  - pip:
    - git+https://github.com/FESOM/pyfesom2.git
